version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: second_service
  rabbitmq:
    image: rabbitmq:3.10.7-management
    restart: always
    ports:
      - "5672:5672"  # AMQP protocol port
      - "15672:15672"# HTTP management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
  api:
    image: second-service
    restart: always
    ports:
      - "8010:80" # http
      - "8011:443"# https
    depends_on:
      - db
      - rabbitmq
    environment:
      RABBITMQ_HOST: host.docker.internal
      RABBITMQ_USER: admin
      RABBITMQ_PASSWORD: admin
      POSTGRESQL: Server=host.docker.internal;Port=5432;Database=second_service;User Id=admin;Password=admin;
